# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7912cd557a9e5ee5cd21359289f8b32084c95426979ef460781be57aac3b4bc75b9b3edb03d5df6bdb72923d8ee322b23862c76297f47ea4038adcb6c1ac34

test:
  secret_key_base: d42e55a58b1aa86109f5da00c9a15f2dcd948a1f1ece7ff4e37303624c1abc3ed1f47b482174d59a2c003019bd6ddcf9024b9c21619846b1d9325bcea8cffa7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
