# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




r1 = Note.create title: 'First Title', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', category: "Math", user_id: 5

r2 = Note.create title: 'First Title', content: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', category: "Science", user_id: 5

r3 = Note.create title: 'First Title', content: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', category: "Spanish", user_id: 5




l1 = Language.create name: 'Afrikaans', abbreviation: 'af'
l2 = Language.create name: 'Albanian', abbreviation: 'sq'
l3 = Language.create name: 'Arabic', abbreviation: 'ar'
l4 = Language.create name: 'Armenian', abbreviation: 'hy'
l5 = Language.create name: 'Azerbaijani', abbreviation: 'az'
l6 = Language.create name: 'Basque', abbreviation: 'eu'
l7 = Language.create name: 'Belarusian', abbreviation: 'be'
l8 = Language.create name: 'Bengali', abbreviation: 'bn'
l9 = Language.create name: 'Bosnian', abbreviation: 'bs'
l10 = Language.create name: 'Bulgarian', abbreviation: 'bg'
l11 = Language.create name: 'Catalan', abbreviation: 'ca'
l12 = Language.create name: 'Cebuano', abbreviation: 'ceb'
l13 = Language.create name: 'Chichewa', abbreviation: 'ny'
l14 = Language.create name: 'Chinese Simplified', abbreviation: 'zh-CN'
l15 = Language.create name: 'Chinese Traditional', abbreviation: 'zh-TW'
l16 = Language.create name: 'Croatian', abbreviation: 'hr'
l17 = Language.create name: 'Czech', abbreviation: 'cs'
l18 = Language.create name: 'Danish', abbreviation: 'da'
l19 = Language.create name: 'Dutch', abbreviation: 'nl'
l20 = Language.create name: 'English', abbreviation: 'en'
l21 = Language.create name: 'Esperanto', abbreviation: 'eo'
l22 = Language.create name: 'Estonian', abbreviation: 'et'
l23 = Language.create name: 'Filipino', abbreviation: 'tl'
l24 = Language.create name: 'Finnish', abbreviation: 'fi'
l25 = Language.create name: 'French', abbreviation: 'fr'
l26 = Language.create name: 'Galician', abbreviation: 'gl'
l27 = Language.create name: 'Georgian', abbreviation: 'ka'
l28 = Language.create name: 'German', abbreviation: 'de'
l29 = Language.create name: 'Greek', abbreviation: 'el'
l30 = Language.create name: 'Gujarati', abbreviation: 'gu'
l31 = Language.create name: 'Haitian Creole', abbreviation: 'ht'
l32 = Language.create name: 'Hausa', abbreviation: 'ha'
l33 = Language.create name: 'Hebrew', abbreviation: 'iw'
l34 = Language.create name: 'Hindi', abbreviation: 'hi'
l35 = Language.create name: 'Hmong', abbreviation: 'hmn'
l36 = Language.create name: 'Hungarian', abbreviation: 'hu'
l37 = Language.create name: 'Icelandic', abbreviation: 'is'
l38 = Language.create name: 'Igbo', abbreviation: 'ig'
l39 = Language.create name: 'Indonesian', abbreviation: 'id'
l40 = Language.create name: 'Irish', abbreviation: 'ga'
l41 = Language.create name: 'Italian', abbreviation: 'it'
l42 = Language.create name: 'Japanese', abbreviation: 'ja'
l43 = Language.create name: 'Javanese', abbreviation: 'jw'
l44 = Language.create name: 'Kannada', abbreviation: 'kn'
l45 = Language.create name: 'Kazakh', abbreviation: 'kk'
l46 = Language.create name: 'Khmer', abbreviation: 'km'
l47 = Language.create name: 'Korean', abbreviation: 'ko'
l48 = Language.create name: 'Lao', abbreviation: 'lo'
l49 = Language.create name: 'Latin', abbreviation: 'la'
l50 = Language.create name: 'Latvian', abbreviation: 'lv'
l51 = Language.create name: 'Lithuanian', abbreviation: 'lt'
l52 = Language.create name: 'Macedonian', abbreviation: 'mk'
l53 = Language.create name: 'Malagasy', abbreviation: 'mg'
l54 = Language.create name: 'Malay', abbreviation: 'ms'
l55 = Language.create name: 'Malayalam', abbreviation: 'ml'
l56 = Language.create name: 'Maltese', abbreviation: 'mt'
l57 = Language.create name: 'Maori', abbreviation: 'mi'
l58 = Language.create name: 'Marathi', abbreviation: 'mr'
l59 = Language.create name: 'Mongolian', abbreviation: 'mn'
l60 = Language.create name: 'Myanmar (Burmese)', abbreviation: 'my'
l61 = Language.create name: 'Nepali', abbreviation: 'ne'
l62 = Language.create name: 'Norwegian', abbreviation: 'no'
l63 = Language.create name: 'Persian', abbreviation: 'fa'
l64 = Language.create name: 'Polish', abbreviation: 'pl'
l65 = Language.create name: 'Portuguese', abbreviation: 'pt'
l66 = Language.create name: 'Punjabi', abbreviation: 'ma'
l67 = Language.create name: 'Romanian', abbreviation: 'ro'
l68 = Language.create name: 'Russian', abbreviation: 'ru'
l69 = Language.create name: 'Serbian', abbreviation: 'sr'
l70 = Language.create name: 'Sesotho', abbreviation: 'st'
l71 = Language.create name: 'Sinhala', abbreviation: 'si'
l72 = Language.create name: 'Slovak', abbreviation: 'sk'
l73 = Language.create name: 'Slovenian', abbreviation: 'sl'
l74 = Language.create name: 'Somali', abbreviation: 'so'
l75 = Language.create name: 'Spanish', abbreviation: 'es'
l76 = Language.create name: 'Sudanese', abbreviation: 'su'
l77 = Language.create name: 'Swahili', abbreviation: 'sw'
l78 = Language.create name: 'Swedish', abbreviation: 'sv'
l79 = Language.create name: 'Tajik', abbreviation: 'tg'
l80 = Language.create name: 'Tamil', abbreviation: 'ta'
l81 = Language.create name: 'Telugu', abbreviation: 'te'
l82 = Language.create name: 'Thai', abbreviation: 'th'
l83 = Language.create name: 'Turkish', abbreviation: 'tr'
l84 = Language.create name: 'Ukrainian', abbreviation: 'uk'
l85 = Language.create name: 'Urdu', abbreviation: 'ur'
l86 = Language.create name: 'Uzbek', abbreviation: 'uz'
l87 = Language.create name: 'Vietnamese', abbreviation: 'vi'
l88 = Language.create name: 'Welsh', abbreviation: 'cy'
l89 = Language.create name: 'Yiddish', abbreviation: 'yi'
l90 = Language.create name: 'Yoruba', abbreviation: 'yo'
l91 = Language.create name: 'Zulu', abbreviation: 'zu'
